//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FormClientERP.WebServiceReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceERPSoap", Namespace="http://grupp11.ics.lu.se/ERP/")]
    public partial class WebServiceERP : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllEmployeesRelativesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllEmployeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllSickEmployees2004OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetEmployeeWithMostAbsenceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCronusKeysOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCronusIndexesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCronusTableConstraintsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCronusTablesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCronusTables1OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCronusEmployeeColumnsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCronusEmployeeColumns1OperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteEmployeeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceERP() {
            this.Url = global::FormClientERP.Properties.Settings.Default.FormClientERP_WebServiceReference_WebServiceERP;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloCompletedEventHandler HelloCompleted;
        
        /// <remarks/>
        public event GetAllEmployeesRelativesCompletedEventHandler GetAllEmployeesRelativesCompleted;
        
        /// <remarks/>
        public event GetAllEmployeesCompletedEventHandler GetAllEmployeesCompleted;
        
        /// <remarks/>
        public event GetAllSickEmployees2004CompletedEventHandler GetAllSickEmployees2004Completed;
        
        /// <remarks/>
        public event GetEmployeeWithMostAbsenceCompletedEventHandler GetEmployeeWithMostAbsenceCompleted;
        
        /// <remarks/>
        public event GetCronusKeysCompletedEventHandler GetCronusKeysCompleted;
        
        /// <remarks/>
        public event GetCronusIndexesCompletedEventHandler GetCronusIndexesCompleted;
        
        /// <remarks/>
        public event GetCronusTableConstraintsCompletedEventHandler GetCronusTableConstraintsCompleted;
        
        /// <remarks/>
        public event GetCronusTablesCompletedEventHandler GetCronusTablesCompleted;
        
        /// <remarks/>
        public event GetCronusTables1CompletedEventHandler GetCronusTables1Completed;
        
        /// <remarks/>
        public event GetCronusEmployeeColumnsCompletedEventHandler GetCronusEmployeeColumnsCompleted;
        
        /// <remarks/>
        public event GetCronusEmployeeColumns1CompletedEventHandler GetCronusEmployeeColumns1Completed;
        
        /// <remarks/>
        public event UpdateEmployeeCompletedEventHandler UpdateEmployeeCompleted;
        
        /// <remarks/>
        public event AddEmployeeCompletedEventHandler AddEmployeeCompleted;
        
        /// <remarks/>
        public event DeleteEmployeeCompletedEventHandler DeleteEmployeeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/Hello", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Hello() {
            object[] results = this.Invoke("Hello", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloAsync() {
            this.HelloAsync(null);
        }
        
        /// <remarks/>
        public void HelloAsync(object userState) {
            if ((this.HelloOperationCompleted == null)) {
                this.HelloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloOperationCompleted);
            }
            this.InvokeAsync("Hello", new object[0], this.HelloOperationCompleted, userState);
        }
        
        private void OnHelloOperationCompleted(object arg) {
            if ((this.HelloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloCompleted(this, new HelloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/GetAllEmployeesRelatives", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetAllEmployeesRelatives() {
            object[] results = this.Invoke("GetAllEmployeesRelatives", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllEmployeesRelativesAsync() {
            this.GetAllEmployeesRelativesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllEmployeesRelativesAsync(object userState) {
            if ((this.GetAllEmployeesRelativesOperationCompleted == null)) {
                this.GetAllEmployeesRelativesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllEmployeesRelativesOperationCompleted);
            }
            this.InvokeAsync("GetAllEmployeesRelatives", new object[0], this.GetAllEmployeesRelativesOperationCompleted, userState);
        }
        
        private void OnGetAllEmployeesRelativesOperationCompleted(object arg) {
            if ((this.GetAllEmployeesRelativesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllEmployeesRelativesCompleted(this, new GetAllEmployeesRelativesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/GetAllEmployees", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetAllEmployees() {
            object[] results = this.Invoke("GetAllEmployees", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllEmployeesAsync() {
            this.GetAllEmployeesAsync(null);
        }
        
        /// <remarks/>
        public void GetAllEmployeesAsync(object userState) {
            if ((this.GetAllEmployeesOperationCompleted == null)) {
                this.GetAllEmployeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllEmployeesOperationCompleted);
            }
            this.InvokeAsync("GetAllEmployees", new object[0], this.GetAllEmployeesOperationCompleted, userState);
        }
        
        private void OnGetAllEmployeesOperationCompleted(object arg) {
            if ((this.GetAllEmployeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllEmployeesCompleted(this, new GetAllEmployeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/GetAllSickEmployees2004", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetAllSickEmployees2004() {
            object[] results = this.Invoke("GetAllSickEmployees2004", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllSickEmployees2004Async() {
            this.GetAllSickEmployees2004Async(null);
        }
        
        /// <remarks/>
        public void GetAllSickEmployees2004Async(object userState) {
            if ((this.GetAllSickEmployees2004OperationCompleted == null)) {
                this.GetAllSickEmployees2004OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllSickEmployees2004OperationCompleted);
            }
            this.InvokeAsync("GetAllSickEmployees2004", new object[0], this.GetAllSickEmployees2004OperationCompleted, userState);
        }
        
        private void OnGetAllSickEmployees2004OperationCompleted(object arg) {
            if ((this.GetAllSickEmployees2004Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllSickEmployees2004Completed(this, new GetAllSickEmployees2004CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/GetEmployeeWithMostAbsence", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetEmployeeWithMostAbsence() {
            object[] results = this.Invoke("GetEmployeeWithMostAbsence", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetEmployeeWithMostAbsenceAsync() {
            this.GetEmployeeWithMostAbsenceAsync(null);
        }
        
        /// <remarks/>
        public void GetEmployeeWithMostAbsenceAsync(object userState) {
            if ((this.GetEmployeeWithMostAbsenceOperationCompleted == null)) {
                this.GetEmployeeWithMostAbsenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetEmployeeWithMostAbsenceOperationCompleted);
            }
            this.InvokeAsync("GetEmployeeWithMostAbsence", new object[0], this.GetEmployeeWithMostAbsenceOperationCompleted, userState);
        }
        
        private void OnGetEmployeeWithMostAbsenceOperationCompleted(object arg) {
            if ((this.GetEmployeeWithMostAbsenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetEmployeeWithMostAbsenceCompleted(this, new GetEmployeeWithMostAbsenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/GetCronusKeys", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetCronusKeys() {
            object[] results = this.Invoke("GetCronusKeys", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetCronusKeysAsync() {
            this.GetCronusKeysAsync(null);
        }
        
        /// <remarks/>
        public void GetCronusKeysAsync(object userState) {
            if ((this.GetCronusKeysOperationCompleted == null)) {
                this.GetCronusKeysOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCronusKeysOperationCompleted);
            }
            this.InvokeAsync("GetCronusKeys", new object[0], this.GetCronusKeysOperationCompleted, userState);
        }
        
        private void OnGetCronusKeysOperationCompleted(object arg) {
            if ((this.GetCronusKeysCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCronusKeysCompleted(this, new GetCronusKeysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/GetCronusIndexes", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetCronusIndexes() {
            object[] results = this.Invoke("GetCronusIndexes", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetCronusIndexesAsync() {
            this.GetCronusIndexesAsync(null);
        }
        
        /// <remarks/>
        public void GetCronusIndexesAsync(object userState) {
            if ((this.GetCronusIndexesOperationCompleted == null)) {
                this.GetCronusIndexesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCronusIndexesOperationCompleted);
            }
            this.InvokeAsync("GetCronusIndexes", new object[0], this.GetCronusIndexesOperationCompleted, userState);
        }
        
        private void OnGetCronusIndexesOperationCompleted(object arg) {
            if ((this.GetCronusIndexesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCronusIndexesCompleted(this, new GetCronusIndexesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/GetCronusTableConstraints", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetCronusTableConstraints() {
            object[] results = this.Invoke("GetCronusTableConstraints", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetCronusTableConstraintsAsync() {
            this.GetCronusTableConstraintsAsync(null);
        }
        
        /// <remarks/>
        public void GetCronusTableConstraintsAsync(object userState) {
            if ((this.GetCronusTableConstraintsOperationCompleted == null)) {
                this.GetCronusTableConstraintsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCronusTableConstraintsOperationCompleted);
            }
            this.InvokeAsync("GetCronusTableConstraints", new object[0], this.GetCronusTableConstraintsOperationCompleted, userState);
        }
        
        private void OnGetCronusTableConstraintsOperationCompleted(object arg) {
            if ((this.GetCronusTableConstraintsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCronusTableConstraintsCompleted(this, new GetCronusTableConstraintsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/GetCronusTables", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetCronusTables() {
            object[] results = this.Invoke("GetCronusTables", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetCronusTablesAsync() {
            this.GetCronusTablesAsync(null);
        }
        
        /// <remarks/>
        public void GetCronusTablesAsync(object userState) {
            if ((this.GetCronusTablesOperationCompleted == null)) {
                this.GetCronusTablesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCronusTablesOperationCompleted);
            }
            this.InvokeAsync("GetCronusTables", new object[0], this.GetCronusTablesOperationCompleted, userState);
        }
        
        private void OnGetCronusTablesOperationCompleted(object arg) {
            if ((this.GetCronusTablesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCronusTablesCompleted(this, new GetCronusTablesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/GetCronusTables1", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetCronusTables1() {
            object[] results = this.Invoke("GetCronusTables1", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetCronusTables1Async() {
            this.GetCronusTables1Async(null);
        }
        
        /// <remarks/>
        public void GetCronusTables1Async(object userState) {
            if ((this.GetCronusTables1OperationCompleted == null)) {
                this.GetCronusTables1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCronusTables1OperationCompleted);
            }
            this.InvokeAsync("GetCronusTables1", new object[0], this.GetCronusTables1OperationCompleted, userState);
        }
        
        private void OnGetCronusTables1OperationCompleted(object arg) {
            if ((this.GetCronusTables1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCronusTables1Completed(this, new GetCronusTables1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/GetCronusEmployeeColumns", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetCronusEmployeeColumns() {
            object[] results = this.Invoke("GetCronusEmployeeColumns", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetCronusEmployeeColumnsAsync() {
            this.GetCronusEmployeeColumnsAsync(null);
        }
        
        /// <remarks/>
        public void GetCronusEmployeeColumnsAsync(object userState) {
            if ((this.GetCronusEmployeeColumnsOperationCompleted == null)) {
                this.GetCronusEmployeeColumnsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCronusEmployeeColumnsOperationCompleted);
            }
            this.InvokeAsync("GetCronusEmployeeColumns", new object[0], this.GetCronusEmployeeColumnsOperationCompleted, userState);
        }
        
        private void OnGetCronusEmployeeColumnsOperationCompleted(object arg) {
            if ((this.GetCronusEmployeeColumnsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCronusEmployeeColumnsCompleted(this, new GetCronusEmployeeColumnsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/GetCronusEmployeeColumns1", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] GetCronusEmployeeColumns1() {
            object[] results = this.Invoke("GetCronusEmployeeColumns1", new object[0]);
            return ((string[][])(results[0]));
        }
        
        /// <remarks/>
        public void GetCronusEmployeeColumns1Async() {
            this.GetCronusEmployeeColumns1Async(null);
        }
        
        /// <remarks/>
        public void GetCronusEmployeeColumns1Async(object userState) {
            if ((this.GetCronusEmployeeColumns1OperationCompleted == null)) {
                this.GetCronusEmployeeColumns1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCronusEmployeeColumns1OperationCompleted);
            }
            this.InvokeAsync("GetCronusEmployeeColumns1", new object[0], this.GetCronusEmployeeColumns1OperationCompleted, userState);
        }
        
        private void OnGetCronusEmployeeColumns1OperationCompleted(object arg) {
            if ((this.GetCronusEmployeeColumns1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCronusEmployeeColumns1Completed(this, new GetCronusEmployeeColumns1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/UpdateEmployee", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateEmployee(string id, string name) {
            this.Invoke("UpdateEmployee", new object[] {
                        id,
                        name});
        }
        
        /// <remarks/>
        public void UpdateEmployeeAsync(string id, string name) {
            this.UpdateEmployeeAsync(id, name, null);
        }
        
        /// <remarks/>
        public void UpdateEmployeeAsync(string id, string name, object userState) {
            if ((this.UpdateEmployeeOperationCompleted == null)) {
                this.UpdateEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEmployeeOperationCompleted);
            }
            this.InvokeAsync("UpdateEmployee", new object[] {
                        id,
                        name}, this.UpdateEmployeeOperationCompleted, userState);
        }
        
        private void OnUpdateEmployeeOperationCompleted(object arg) {
            if ((this.UpdateEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateEmployeeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/AddEmployee", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddEmployee(string id, string name) {
            this.Invoke("AddEmployee", new object[] {
                        id,
                        name});
        }
        
        /// <remarks/>
        public void AddEmployeeAsync(string id, string name) {
            this.AddEmployeeAsync(id, name, null);
        }
        
        /// <remarks/>
        public void AddEmployeeAsync(string id, string name, object userState) {
            if ((this.AddEmployeeOperationCompleted == null)) {
                this.AddEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddEmployeeOperationCompleted);
            }
            this.InvokeAsync("AddEmployee", new object[] {
                        id,
                        name}, this.AddEmployeeOperationCompleted, userState);
        }
        
        private void OnAddEmployeeOperationCompleted(object arg) {
            if ((this.AddEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddEmployeeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp11.ics.lu.se/ERP/DeleteEmployee", RequestNamespace="http://grupp11.ics.lu.se/ERP/", ResponseNamespace="http://grupp11.ics.lu.se/ERP/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteEmployee(string id) {
            this.Invoke("DeleteEmployee", new object[] {
                        id});
        }
        
        /// <remarks/>
        public void DeleteEmployeeAsync(string id) {
            this.DeleteEmployeeAsync(id, null);
        }
        
        /// <remarks/>
        public void DeleteEmployeeAsync(string id, object userState) {
            if ((this.DeleteEmployeeOperationCompleted == null)) {
                this.DeleteEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteEmployeeOperationCompleted);
            }
            this.InvokeAsync("DeleteEmployee", new object[] {
                        id}, this.DeleteEmployeeOperationCompleted, userState);
        }
        
        private void OnDeleteEmployeeOperationCompleted(object arg) {
            if ((this.DeleteEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteEmployeeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void HelloCompletedEventHandler(object sender, HelloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAllEmployeesRelativesCompletedEventHandler(object sender, GetAllEmployeesRelativesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllEmployeesRelativesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllEmployeesRelativesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAllEmployeesCompletedEventHandler(object sender, GetAllEmployeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllEmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllEmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetAllSickEmployees2004CompletedEventHandler(object sender, GetAllSickEmployees2004CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllSickEmployees2004CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllSickEmployees2004CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetEmployeeWithMostAbsenceCompletedEventHandler(object sender, GetEmployeeWithMostAbsenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetEmployeeWithMostAbsenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetEmployeeWithMostAbsenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetCronusKeysCompletedEventHandler(object sender, GetCronusKeysCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCronusKeysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCronusKeysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetCronusIndexesCompletedEventHandler(object sender, GetCronusIndexesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCronusIndexesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCronusIndexesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetCronusTableConstraintsCompletedEventHandler(object sender, GetCronusTableConstraintsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCronusTableConstraintsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCronusTableConstraintsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetCronusTablesCompletedEventHandler(object sender, GetCronusTablesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCronusTablesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCronusTablesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetCronusTables1CompletedEventHandler(object sender, GetCronusTables1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCronusTables1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCronusTables1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetCronusEmployeeColumnsCompletedEventHandler(object sender, GetCronusEmployeeColumnsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCronusEmployeeColumnsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCronusEmployeeColumnsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetCronusEmployeeColumns1CompletedEventHandler(object sender, GetCronusEmployeeColumns1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCronusEmployeeColumns1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCronusEmployeeColumns1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[][] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[][])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateEmployeeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void AddEmployeeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteEmployeeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591